baseURL = "http://coisasdeinfra.com/"
defaultContentLanguage = "pt"
languageCode = "en"
title = "Coisas de Infra"
theme = "LoveIt"
enableRobotsTXT = true

#[languages]
#  [languages.pt]
#    weight = 1
#    # language code
#    languageCode = "en"
#    # language name
#    languageName = "Português BR"
#    # whether to include Chinese/Japanese/Korean
#    hasCJKLanguage = false
#    # default amount of posts in each pages
#    paginate = 12
#    # [UA-XXXXXXXX-X] google analytics code
#    googleAnalytics = ""
#    # copyright description used only for seo schema
#    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
#    # Menu config
#    [languages.pt.menu]
#      [[languages.pt.menu.main]]
#        identifier = "posts"
#        # you can add extra information before the name (HTML format is supported), such as icons
#        pre = ""
#        # you can add extra information after the name (HTML format is supported), such as icons
#        post = ""
#        name = "Posts"
#        url = "/posts/"
#        # title will be shown when you hover on this menu link.
#        title = ""
#        weight = 1
#      [[languages.pt.menu.main]]
#        identifier = "tags"
#      #  pre = ""
#      #  post = ""
#      #  name = "Tags"
#      #  url = "/tags/"
#      #  title = ""
#      #  weight = 2
#      #[[languages.en.menu.main]]
#      #  identifier = "categories"
#      #  pre = ""
#      #  post = ""
#      #  name = "Categories"
#      #  url = "/categories/"
#      #  title = ""
#      #  weight = 3
#      #[[languages.en.menu.main]]
#      #  identifier = "documentation"
#      #  pre = ""
#      #  post = ""
#      #  name = "Docs"
#      #  url = "/categories/documentation/"
#      #  title = ""
#      #  weight = 4
#      [[languages.pt.menu.main]]
#        identifier = "about"
#        pre = ""
#        post = ""
#        name = "Sobre mim"
#        url = "/about/"
#        title = ""
#        weight = 5
#      #[[languages.en.menu.main]]
#      #  identifier = "github"
#      #  pre = "<i class='fab fa-github fa-fw'></i>"
#      #  post = ""
#      #  name = ""
#      #  url = "https://github.com/dillonzq/loveit"
#      #  title = "GitHub"
#      #  weight = 6
#    [languages.pt.params]
#      # site description
#      description = "Compartilhando Conhecimento"
#      # site keywords
#      keywords = ["blog", "Infra", "Linux", "Segurança"]
#      # App icon config
#      [languages.pt.params.app]
#        # optional site title override for the app when added to an iOS home screen or Android launcher
#        title = "Coisas de Infra"
#        # whether to omit favicon resource links
#        noFavicon = false
#        # modern SVG favicon to use in place of older style .png and .ico files
#        svgFavicon = ""
#        # Android browser theme color
#        themeColor = "#ffffff"
#        # Safari mask icon color
#        iconColor = "#5bbad5"
#        # Windows v8-10 tile color
#        tileColor = "#da532c"
#      # Search config
#      [languages.pt.params.search]
#        enable = true
#        # type of search engine ("lunr", "algolia")
#        type = "algolia"
#        # max index length of the chunked content
#        contentLength = 4000
#        # placeholder of the search bar
#        placeholder = ""
#        # max number of results length
#        maxResultLength = 10
#        # snippet length of the result
#        snippetLength = 30
#        # HTML tag name of the highlight part in results
#        highlightTag = "em"
#        # whether to use the absolute URL based on the baseURL in search index
#        absoluteURL = false
#        [languages.en.params.search.algolia]
#          index = "index.en"
#          appID = "PASDMWALPK"
#          searchKey = "b42948e51daaa93df92381c8e2ac0f93"
#      # Home page config
#      [languages.pt.params.home]
#        # amount of RSS pages
#        #rss = 10
#        # Home page profile
#        [languages.pt.params.home.profile]
#          enable = true
#          # Gravatar Email for preferred avatar in home page
#          gravatarEmail = ""
#          # URL of avatar shown in home page
#          avatarURL = "/images/matheus.png"
#          # title shown in home page (HTML format is supported)
#          title = "Coisas de Infra"
#          # subtitle shown in home page
#          subtitle = "Compartilhando Conhecimento"
#          # whether to use typeit animation for subtitle
#          typeit = true
#          # whether to show social links
#          social = true
#          # disclaimer (HTML format is supported)
#          disclaimer = ""
#        # Home page posts
#        [languages.pt.params.home.posts]
#          enable = true
#          # special amount of posts in each home posts page
#          paginate = 6
#      # Social config in home page
#      [languages.en.params.social]
#        GitHub = "xxxx"
#        Linkedin = ""
#        #Twitter = "xxxx"
#        #Instagram = "xxxx"
#        #Facebook = "xxxx"
#        #Telegram = "xxxx"
#        #Medium = ""
#        #Gitlab = ""
#        #Youtubelegacy = "xxxx"
#        #Youtubecustom = ""
#        #Youtubechannel = ""
#        #Tumblr = ""
#        #Quora = ""
#        #Keybase = ""
#        #Pinterest = ""
#        #Reddit = ""
#        #Codepen = ""
#        #FreeCodeCamp = ""
#        #Bitbucket = ""
#        #Stackoverflow = ""
#        #Weibo = ""
#        #Odnoklassniki = ""
#        #VK = ""
#        #Flickr = ""
#        #Xing = ""
#        ##Snapchat = ""
#        #Soundcloud = ""
#        #Spotify = ""
#        #Bandcamp = ""
#        #Paypal = ""
#        #Fivehundredpx = ""
#        #Mix = ""
#        #Goodreads = ""
#        #Lastfm = ""
#        #Foursquare = ""
#        #Hackernews = ""
#        #Kickstarter = ""
#        #Patreon = ""
#        #Steam = ""
#        #Twitch = ""
#        #Strava = ""
#        #Skype = ""
#        #Whatsapp = ""
#        #Zhihu = ""
#        #Douban = ""
#        #Angellist = ""
#        #Slidershare = ""
#        #Jsfiddle = ""
#        #Deviantart = ""
#        #Behance = ""
#        #Dribbble = ""
#        #Wordpress = ""
#        #Vine = ""
#        #Googlescholar = ""
#        #Researchgate = ""
#        #Thingiverse = ""
#        #Devto = ""
#        #Gitea = ""
#        #XMPP = ""
#        #Matrix = ""
#        #Bilibili = ""
#        #Email = "xxxx@xxxx.com"
#        #RSS = true
#        #[languages.en.params.social.Mastodon]
#        #  id = "@xxxx"
#        #  prefix = "https://mastodon.technology/"



[params]
  #LoveIt theme version
  version = "0.2.X"
  description = "Compartilhando Conhecimento"
  defaultTheme = "auto"
  images = ["/coisasdeinfra.png"]
  dateFormat = "02-01-2006"

[params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Coisas De Infra"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"

# Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/coisasdeinfraLogo.png"
      # title name
      name = ""
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

# Footer config
  [params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = true
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2018
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# LoveIt NEW | 0.2.0 Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "02-01"
    # amount of RSS pages
    #rss = 10

# LoveIt NEW | 0.2.0 List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "02-01"
    # amount of RSS pages
    #rss = 10




  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # LoveIt NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # LoveIt NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
    highlightTag = "em"
    # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""


  






  



  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    #rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/matheus-linkedin.jpeg"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Coisas de Infra"
      # subtitle shown in home page
      subtitle = "Compartilhando Conhecimento"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Social config about the author
  [params.social]
  GitHub = "MatheusQ"
  Linkedin = "matheus-dias-queiroz/"

  [params.page]
    # LoveIt NEW | 0.2.0 whether to hide a page from home page
    hiddenFromHomePage = false
    # LoveIt NEW | 0.2.0 whether to hide a page from search results
    hiddenFromSearch = false
    # LoveIt NEW | 0.2.0 whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = false
    # LoveIt NEW | 0.2.0 whether to enable the ruby extended syntax
    ruby = true
    # LoveIt NEW | 0.2.0 whether to enable the fraction extended syntax
    fraction = true
    # LoveIt NEW | 0.2.0 whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # LoveIt NEW | 0.2.4 whether to show the full text content in RSS
    rssFullText = false
    # LoveIt NEW | 0.2.0 Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # LoveIt NEW | 0.2.9 whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    # Code config
    # 代码配置
    [params.page.code]
      # whether to show the copy button of the code block
      # 是否显示代码块的复制按钮
      copy = true
      # the maximum number of lines of displayed code by default
      # 默认展开显示的代码行数
      maxShownLines = 1000
    # KaTeX mathematical formulas config (KaTeX https://katex.org/)
    # KaTeX 数学公式配置 (KaTeX https://katex.org/)

    [params.page.math]
      enable = false
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true
    # LoveIt NEW | 0.2.0 Code config

    # LoveIt NEW | 0.2.0 Mapbox GL JS config
    [params.page.mapbox]
      # access token of Mapbox GL JS
      accessToken = ""
      # style for the light theme
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # style for the dark theme
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # whether to add NavigationControl
      navigation = true
      # whether to add GeolocateControl
      geolocate = true
      # whether to add ScaleControl
      scale = true
      # whether to add FullscreenControl
      fullscreen = true
    # LoveIt CHANGED | 0.2.0 social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = false
      Renren = false
      Myspace = false
      Blogger = true
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = true
      Mix = false
    # LoveIt CHANGED | 0.2.0 Comment config
    [params.page.comment]
      enable = true
      # Disqus comment config
      [params.page.comment.disqus]
        # LoveIt NEW | 0.1.1
        enable = true
        # Disqus shortname to use Disqus in posts
        shortname = ""

  # LoveIt NEW | 0.2.5 TypeIt config
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

  
  # LoveIt NEW | 0.2.0 Analytics config
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = ""
      # whether to anonymize IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # server url for your tracker if you're self hosting
      server = ""


  # LoveIt NEW | 0.2.7 Cookie consent config
  [params.cookieconsent]
    enable = false
    # text strings used for Cookie consent banner
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  # LoveIt NEW | 0.2.8 Compatibility config
  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    objectFit = false


# Markup related config in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6

# Author config
[author]
  name = "Matheus Dias Queiroz"
  email = ""
  link = "http://coisasdeinfra.com/about"

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Privacy config
[privacy]
  # LoveIt DELETED | 0.2.0 privacy of the Google Analytics (replaced by params.analytics.google)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  # LoveIt CHANGED | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]


[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  #[[menu.main]]
  #  identifier = "categories"
  #  pre = ""
  #  post = ""
  #  name = "Categories"
  #  url = "/categories/"
  #  title = ""
  #  weight = 3
